/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AwdsAccordion {
    }
    interface AwdsAccordionItem {
        /**
          * Heading text
         */
        "heading": string;
        /**
          * Open state
          * @default false
         */
        "open": boolean;
    }
    interface AwdsButton {
        /**
          * Disabled state
          * @default false
         */
        "disabled": boolean;
        /**
          * Size
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * Button type
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Visual style
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary' | 'tertiary';
    }
    interface AwdsCheckbox {
        /**
          * Checked state
          * @default false
         */
        "checked": boolean;
        /**
          * Disabled state
          * @default false
         */
        "disabled": boolean;
        /**
          * Visible label
         */
        "label"?: string;
        /**
          * Checkbox name for forms
         */
        "name"?: string;
        /**
          * Checkbox value
          * @default 'on'
         */
        "value": string;
    }
    interface AwdsModal {
        "close": () => Promise<void>;
        /**
          * Modal heading
          * @default 'Modal title'
         */
        "heading": string;
        /**
          * Modal open state
          * @default false
         */
        "open": boolean;
        "show": () => Promise<void>;
    }
    interface AwdsSideDrawer {
        "open": () => Promise<void>;
        "opened": boolean;
        "title": string;
    }
    interface AwdsSpinner {
    }
    interface AwdsStockFinder {
    }
    interface AwdsStockPrice {
        "stockSymbol": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
}
export interface AwdsStockFinderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAwdsStockFinderElement;
}
declare global {
    interface HTMLAwdsAccordionElement extends Components.AwdsAccordion, HTMLStencilElement {
    }
    var HTMLAwdsAccordionElement: {
        prototype: HTMLAwdsAccordionElement;
        new (): HTMLAwdsAccordionElement;
    };
    interface HTMLAwdsAccordionItemElement extends Components.AwdsAccordionItem, HTMLStencilElement {
    }
    var HTMLAwdsAccordionItemElement: {
        prototype: HTMLAwdsAccordionItemElement;
        new (): HTMLAwdsAccordionItemElement;
    };
    interface HTMLAwdsButtonElement extends Components.AwdsButton, HTMLStencilElement {
    }
    var HTMLAwdsButtonElement: {
        prototype: HTMLAwdsButtonElement;
        new (): HTMLAwdsButtonElement;
    };
    interface HTMLAwdsCheckboxElement extends Components.AwdsCheckbox, HTMLStencilElement {
    }
    var HTMLAwdsCheckboxElement: {
        prototype: HTMLAwdsCheckboxElement;
        new (): HTMLAwdsCheckboxElement;
    };
    interface HTMLAwdsModalElement extends Components.AwdsModal, HTMLStencilElement {
    }
    var HTMLAwdsModalElement: {
        prototype: HTMLAwdsModalElement;
        new (): HTMLAwdsModalElement;
    };
    interface HTMLAwdsSideDrawerElement extends Components.AwdsSideDrawer, HTMLStencilElement {
    }
    var HTMLAwdsSideDrawerElement: {
        prototype: HTMLAwdsSideDrawerElement;
        new (): HTMLAwdsSideDrawerElement;
    };
    interface HTMLAwdsSpinnerElement extends Components.AwdsSpinner, HTMLStencilElement {
    }
    var HTMLAwdsSpinnerElement: {
        prototype: HTMLAwdsSpinnerElement;
        new (): HTMLAwdsSpinnerElement;
    };
    interface HTMLAwdsStockFinderElementEventMap {
        "awSymbolSelected": string;
    }
    interface HTMLAwdsStockFinderElement extends Components.AwdsStockFinder, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAwdsStockFinderElementEventMap>(type: K, listener: (this: HTMLAwdsStockFinderElement, ev: AwdsStockFinderCustomEvent<HTMLAwdsStockFinderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAwdsStockFinderElementEventMap>(type: K, listener: (this: HTMLAwdsStockFinderElement, ev: AwdsStockFinderCustomEvent<HTMLAwdsStockFinderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAwdsStockFinderElement: {
        prototype: HTMLAwdsStockFinderElement;
        new (): HTMLAwdsStockFinderElement;
    };
    interface HTMLAwdsStockPriceElement extends Components.AwdsStockPrice, HTMLStencilElement {
    }
    var HTMLAwdsStockPriceElement: {
        prototype: HTMLAwdsStockPriceElement;
        new (): HTMLAwdsStockPriceElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "awds-accordion": HTMLAwdsAccordionElement;
        "awds-accordion-item": HTMLAwdsAccordionItemElement;
        "awds-button": HTMLAwdsButtonElement;
        "awds-checkbox": HTMLAwdsCheckboxElement;
        "awds-modal": HTMLAwdsModalElement;
        "awds-side-drawer": HTMLAwdsSideDrawerElement;
        "awds-spinner": HTMLAwdsSpinnerElement;
        "awds-stock-finder": HTMLAwdsStockFinderElement;
        "awds-stock-price": HTMLAwdsStockPriceElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface AwdsAccordion {
    }
    interface AwdsAccordionItem {
        /**
          * Heading text
         */
        "heading": string;
        /**
          * Open state
          * @default false
         */
        "open"?: boolean;
    }
    interface AwdsButton {
        /**
          * Disabled state
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Size
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * Button type
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Visual style
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'tertiary';
    }
    interface AwdsCheckbox {
        /**
          * Checked state
          * @default false
         */
        "checked"?: boolean;
        /**
          * Disabled state
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Visible label
         */
        "label"?: string;
        /**
          * Checkbox name for forms
         */
        "name"?: string;
        /**
          * Checkbox value
          * @default 'on'
         */
        "value"?: string;
    }
    interface AwdsModal {
        /**
          * Modal heading
          * @default 'Modal title'
         */
        "heading"?: string;
        /**
          * Modal open state
          * @default false
         */
        "open"?: boolean;
    }
    interface AwdsSideDrawer {
        "opened"?: boolean;
        "title"?: string;
    }
    interface AwdsSpinner {
    }
    interface AwdsStockFinder {
        "onAwSymbolSelected"?: (event: AwdsStockFinderCustomEvent<string>) => void;
    }
    interface AwdsStockPrice {
        "stockSymbol"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }

    interface AwdsAccordionItemAttributes {
        "heading": string;
        "open": boolean;
    }
    interface AwdsButtonAttributes {
        "variant": 'primary' | 'secondary' | 'tertiary';
        "size": 'sm' | 'md' | 'lg';
        "disabled": boolean;
        "type": 'button' | 'submit' | 'reset';
    }
    interface AwdsCheckboxAttributes {
        "name": string;
        "value": string;
        "label": string;
        "checked": boolean;
        "disabled": boolean;
    }
    interface AwdsModalAttributes {
        "open": boolean;
        "heading": string;
    }
    interface AwdsSideDrawerAttributes {
        "title": string;
        "opened": boolean;
    }
    interface AwdsStockPriceAttributes {
        "stockSymbol": string;
    }
    interface MyComponentAttributes {
        "first": string;
        "middle": string;
        "last": string;
    }

    interface IntrinsicElements {
        "awds-accordion": AwdsAccordion;
        "awds-accordion-item": Omit<AwdsAccordionItem, keyof AwdsAccordionItemAttributes> & { [K in keyof AwdsAccordionItem & keyof AwdsAccordionItemAttributes]?: AwdsAccordionItem[K] } & { [K in keyof AwdsAccordionItem & keyof AwdsAccordionItemAttributes as `attr:${K}`]?: AwdsAccordionItemAttributes[K] } & { [K in keyof AwdsAccordionItem & keyof AwdsAccordionItemAttributes as `prop:${K}`]?: AwdsAccordionItem[K] } & OneOf<"heading", AwdsAccordionItem["heading"], AwdsAccordionItemAttributes["heading"]>;
        "awds-button": Omit<AwdsButton, keyof AwdsButtonAttributes> & { [K in keyof AwdsButton & keyof AwdsButtonAttributes]?: AwdsButton[K] } & { [K in keyof AwdsButton & keyof AwdsButtonAttributes as `attr:${K}`]?: AwdsButtonAttributes[K] } & { [K in keyof AwdsButton & keyof AwdsButtonAttributes as `prop:${K}`]?: AwdsButton[K] };
        "awds-checkbox": Omit<AwdsCheckbox, keyof AwdsCheckboxAttributes> & { [K in keyof AwdsCheckbox & keyof AwdsCheckboxAttributes]?: AwdsCheckbox[K] } & { [K in keyof AwdsCheckbox & keyof AwdsCheckboxAttributes as `attr:${K}`]?: AwdsCheckboxAttributes[K] } & { [K in keyof AwdsCheckbox & keyof AwdsCheckboxAttributes as `prop:${K}`]?: AwdsCheckbox[K] };
        "awds-modal": Omit<AwdsModal, keyof AwdsModalAttributes> & { [K in keyof AwdsModal & keyof AwdsModalAttributes]?: AwdsModal[K] } & { [K in keyof AwdsModal & keyof AwdsModalAttributes as `attr:${K}`]?: AwdsModalAttributes[K] } & { [K in keyof AwdsModal & keyof AwdsModalAttributes as `prop:${K}`]?: AwdsModal[K] };
        "awds-side-drawer": Omit<AwdsSideDrawer, keyof AwdsSideDrawerAttributes> & { [K in keyof AwdsSideDrawer & keyof AwdsSideDrawerAttributes]?: AwdsSideDrawer[K] } & { [K in keyof AwdsSideDrawer & keyof AwdsSideDrawerAttributes as `attr:${K}`]?: AwdsSideDrawerAttributes[K] } & { [K in keyof AwdsSideDrawer & keyof AwdsSideDrawerAttributes as `prop:${K}`]?: AwdsSideDrawer[K] };
        "awds-spinner": AwdsSpinner;
        "awds-stock-finder": AwdsStockFinder;
        "awds-stock-price": Omit<AwdsStockPrice, keyof AwdsStockPriceAttributes> & { [K in keyof AwdsStockPrice & keyof AwdsStockPriceAttributes]?: AwdsStockPrice[K] } & { [K in keyof AwdsStockPrice & keyof AwdsStockPriceAttributes as `attr:${K}`]?: AwdsStockPriceAttributes[K] } & { [K in keyof AwdsStockPrice & keyof AwdsStockPriceAttributes as `prop:${K}`]?: AwdsStockPrice[K] };
        "my-component": Omit<MyComponent, keyof MyComponentAttributes> & { [K in keyof MyComponent & keyof MyComponentAttributes]?: MyComponent[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `attr:${K}`]?: MyComponentAttributes[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `prop:${K}`]?: MyComponent[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "awds-accordion": LocalJSX.IntrinsicElements["awds-accordion"] & JSXBase.HTMLAttributes<HTMLAwdsAccordionElement>;
            "awds-accordion-item": LocalJSX.IntrinsicElements["awds-accordion-item"] & JSXBase.HTMLAttributes<HTMLAwdsAccordionItemElement>;
            "awds-button": LocalJSX.IntrinsicElements["awds-button"] & JSXBase.HTMLAttributes<HTMLAwdsButtonElement>;
            "awds-checkbox": LocalJSX.IntrinsicElements["awds-checkbox"] & JSXBase.HTMLAttributes<HTMLAwdsCheckboxElement>;
            "awds-modal": LocalJSX.IntrinsicElements["awds-modal"] & JSXBase.HTMLAttributes<HTMLAwdsModalElement>;
            "awds-side-drawer": LocalJSX.IntrinsicElements["awds-side-drawer"] & JSXBase.HTMLAttributes<HTMLAwdsSideDrawerElement>;
            "awds-spinner": LocalJSX.IntrinsicElements["awds-spinner"] & JSXBase.HTMLAttributes<HTMLAwdsSpinnerElement>;
            "awds-stock-finder": LocalJSX.IntrinsicElements["awds-stock-finder"] & JSXBase.HTMLAttributes<HTMLAwdsStockFinderElement>;
            "awds-stock-price": LocalJSX.IntrinsicElements["awds-stock-price"] & JSXBase.HTMLAttributes<HTMLAwdsStockPriceElement>;
            "my-component": LocalJSX.IntrinsicElements["my-component"] & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
